DefaultMOTD:
    - '          &eThis is the first line'
    - '    &4This is the second line!'
SecondaryMOTD:
    - '          This is the first line'
    - '    &4This is the second line!'
COUNTER: 0

CUSTOM_MOTDS:
    MOTD1NameHere:
        ACTIVE: false
        LINES:
        - '          &cThis is the first line'
        - '    &4This is the second line!'
    MOTD2NameHere:
        ACTIVE: false
        LINES:
        - '          &4This is the first line'
        - '    &4This is the second line!'